package com.trx.topic

object Topic {
    const val CHECK_PRODUCT = "CHECK-PRODUCT"
    const val APPLY_PAYMENT = "APPLY-PAYMENT"

    const val CHECK_PRODUCT_SUCCEED = "CHECK-PRODUCT-SUCCEED"
    const val CHECK_PRODUCT_FAILED = "CHECK-PRODUCT-FAILED"

    const val PAYMENT_SUCCEED = "PAYMENT-SUCCEED"
    const val PAYMENT_FAILED = "PAYMENT-FAILED"

    const val CHECK_PRODUCT_ROLLBACK = "CHECK-PRODUCT-ROLLBACK"

    // transaction
    const val ORDER_CREATED = "ORDER-CREATED"

    const val ORDER_CANCELED = "ORDER-CANCELED"
    const val ORDER_APPROVED = "ORDER-APPROVED"
}