package com.trx.topic

object Topic {
    const val CHECK_PRODUCT = "CHECK-PRODUCT"
    const val APPLY_PAYMENT = "APPLY-PAYMENT"

    const val CHECK_PRODUCT_COMPLETED = "CHECK-PRODUCT-COMPLETED"
    const val CHECK_PRODUCT_FAILED = "CHECK-PRODUCT-FAILED"

    const val PAYMENT_COMPLETED = "PAYMENT-COMPLETED"
    const val PAYMENT_FAILED = "PAYMENT-FAILED"

    const val PRODUCT_ROLLBACK = "PRODUCT-ROLLBACK"


    const val ORDER_CREATED = "ORDER-CREATED"
    const val ORDER_ROLLBACKED = "ORDER_ROLLBACKED"

    const val ORDER_FAILED = "ORDER-FAILED"
    const val ORDER_COMPLETED = "ORDER-COMPLETED"
}